#   Cloudflare DDNS script by Jasper
#   GitHub: https://github.com/j4asper
#   Repo: https://github.com/j4asper/ddns

# Your cloudflare global api key. Find it at:
# My Profile > API Tokens > Global API Key > View, input your password, and copy the key.
Global-API-Key: b52359cac5235hg23hjgvjh48997b2d21dbb4e91b

# What DNS record type do you want to update? If you are using this as an Dynamic DNS,
# an A record would be the most suitable. You can only use an A or AAAA record here!
Record-Type: A

# Your cloudflare mail, the one you use to login to cloudflare with.
CloudFlare-email: YourMail@example.com

# Your root domain name
Domain: example.com

# If you are using your root domain for the dynamic dns, set this to true.
using-root-domain: false

# The subdomain name you want to update, this is without the root domain,
# so if your want to update home.example.com you would only put home here.
# If you are using your root domain, leave this empty.
Subdomain: home

# Time-to-live for your A record. It should be as low as possible since you don't want it to be cached for too long.
# The minimum is 120, if you don't know what this does, just leave it as it is.
TTL: "120"
